### ISSUE TITLE
Digits Validator doesn't accept strings of arbitrary length

### ISSUE THREAD

**Issue by tggm** [srkirkland/DataAnnotationsExtensions#56]
The Digits() validator is based on the Long.Parse() function, which limits the allowable strings to the maximum value a long value type can hold.

For example, an european account number of 21 digits will fail the validator.

Thank you

**Comment by srkirkland** [comment]
Ok fixed in latest master to just be a regex like it should have been the whole time.  Release 1.2 will have the fix.
