### ISSUE TITLE
UrlOptions.OptionalProtocol doesn't work

### ISSUE THREAD

**Issue by klyakh** [srkirkland/DataAnnotationsExtensions#58]
Using it in ASP.NET MVC 5.1 project (haven't tried to reproduce it on earlier versions).

Have the following attribute applied:
[DataAnnotationsExtensions.Url(UrlOptions.OptionalProtocol)]
public string Domain { get; set; }

If I enter "domain.com" it says "Please enter a valid URL." I guess it conflicts with standard DataType.Url validation.

**Comment by srkirkland** [comment]
Works for me on the old MVC3 stuff that is published now -- I'm working on an MVC5 version so I'll tag this to look into for that release
