### ISSUE TITLE
Min attribute incorrectly fires when the minimum is a single digit

### ISSUE THREAD

**Issue by tommytayman** [srkirkland/DataAnnotationsExtensions#60]
I have an integer property with the Min attribute set to 5.  When using jQuery.unobtrusive validation plugin, jQuery will mark any value not starting with a 5 or greater as invalid and show the corresponding error message.  Meaning the values 5 through 9 as well as 50-99, 500-999 etc all will pass validation.  Any value not starting with a 5 or greater such as 10-49, 100-499, etc. will fail the javascript validation and display the error message.  When the minimum is set to 10 or higher, the validation attributes all work as expected.

I confirmed this on a clean MVC 5 project using the following versions:

- jQuery 1.8.2 and higher (including 2.x branch)
- jQuery.validation - 1.11.0 (current as of this issue report)
- jQuery unobtrusive validation 3.1.2 (current as of this issue report)

The work around is to use the Range() attribute within the .NET framework.  Additional information located here - http://stackoverflow.com/questions/23687162/mvc-unobtrusive-validation-incorrectly-firing

**Comment by srkirkland** [comment]
seems to be specific to mvc 5 since the version currently using using the old MVC3 stuff is working.  I'm going to build out an MVC5 version here soon so i'll keep this around to make sure to fix it.
