### ISSUE TITLE
support for MVC5

### ISSUE THREAD

**Issue by valle72** [srkirkland/DataAnnotationsExtensions#64]
Is there any date to get a release for MVC5?
Mainly Date validation is not working at all...

**Comment by nunofilipecosta** [comment]
Anyone ?

**Comment by sebrojas14** [comment]
So bad :(

**Comment by srkirkland** [comment]
@valle72 @nunofilipecosta @sebrojas14 Support for MVC 5 is now available in the https://www.nuget.org/packages/DataAnnotationsExtensions.MVC page, version 5.*.  Date validation should work correctly now, along with a few other lingering issues.
