### ISSUE TITLE
Missing the list of Validations in Wiki

### ISSUE THREAD

**Issue by TioNoob** [srkirkland/DataAnnotationsExtensions#66]
Because your site contains the word "sex" ( http://dataannotation**sex**tensions.org/ ) our proxy is blocking it.
A good ideia is to add the list of Validators on Wiki.

**Comment by srkirkland** [comment]
Ha that's funny -- here's the list.  I'll make a page on the Wiki for it:

CreditCardAttribute
CuitAttribute
DateAttribute
DigitsAttribute
EmailAttribute
EqualToAttribute
FileExtensionsAttribute
IntegerAttribute
MaxAttribute
MinAttribute
NumericAttribute
UrlAttribute
YearAttribute

**Comment by srkirkland** [comment]
@TioNoob Ok it's on the wiki mainpage now:

https://github.com/srkirkland/DataAnnotationsExtensions/wiki

**Comment by TioNoob** [comment]
I thought the same thing ^^
Thanks for the help.
