### ISSUE TITLE
What's the difference between DataAnnotationsExtensions.MVC3 and DataAnnotationsExtensions.MVC packages?

### ISSUE THREAD

**Issue by exalted** [srkirkland/DataAnnotationsExtensions#73]
I wonder what's the difference between [DataAnnotationsExtensions.MVC3](https://www.nuget.org/packages/DataAnnotationsExtensions.MVC3/) and [DataAnnotationsExtensions.MVC](https://www.nuget.org/packages/DataAnnotationsExtensions.MVC/) packages please?

Thank you.

**Comment by azzimuth** [comment]
MVC3 one supports ASP.NET MVC3. MVC one supports MVC4 and 5, as far as I understand.

**Comment by exalted** [comment]
@azzimuth thanks!
