### ISSUE TITLE
A strongly-named assembly is required

### ISSUE THREAD

**Issue by sealight** [srkirkland/DataAnnotationsExtensions#74]
DataAnnotationsModelValidatorProviderExtensions.RegisterValidationExtensions();        
fail with
Could not load file or assembly 'DataAnnotationsExtensions.ClientValidation, Version=5.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. 

Can't you strongly-name the assembly?

**Comment by srkirkland** [comment]
@sealight Problem is strongly-named assemblies are a pain when it comes to versioning and over the last few years it is less common to find open source repositories strong signing their assemblies. 

Jeremy Miller wrote up a good post about SN problems in open source  https://jeremydmiller.com/2014/04/28/fubumvc-lessons-learned-strong-naming-woes-and-workarounds/

If you really really have to strong name though there are plenty of ways to do it after the fact, see something like https://blog.maartenballiauw.be/post/2014/09/10/automatically-strong-name-signing-nuget-packages.html.
