### ISSUE TITLE
broken dependency on WebActivator

### ISSUE THREAD

**Issue by Spongman** [srkirkland/DataAnnotationsExtensions#75]
DataAnnotationsExtensions.MVC3 depends on WebActivator, which is deprecated.

also, after installation RegisterClientValidationExtensions.cs includes a reference to WebActivatorEx which is not installed.

the dependency needs to be updated to WebActivatorEx.

**Comment by srkirkland** [comment]
Good to know, I'll change the dependency to WebActivatorEx and see if it breaks/changes anything, and if not I'll push out a new version with that change.

**Comment by srkirkland** [comment]
@Spongman ok, the newest version https://www.nuget.org/packages/DataAnnotationsExtensions.MVC3/5.0.1.18 now depends on WebActivatorEx (>= 2.1.0) which should work.  Thanks for pointing this out.
